# Site settings
title: Enji
email: mail@ngjuliann.com
url: http://ngjuliann.com
description: "ngjuliann.com home of Julian Ng"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Julian Joyan Ng

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url: 
  - title: github
    url: 

# Build settings
markdown: kramdown
permalink: pretty

# Google Analytics
google_analytics: UAâ€”71267387-1


